### get cart
GET http://localhost:3000/cart

### get product
GET http://localhost:3000/cart/09a44170-61c9-4682-8d6e-7bcfeb95bc1a


###
GET http://localhost:3000/cart/by-product/111/br

### add produt
POST http://localhost:3000/cart
Content-Type: application/json

{
    "productId": "1",
    "name": "Produto Teste 1",
    "price": 99.9,
    "quantity": 2,
    "img": "ffdfdf",
    "origin":"br"
}



###
PATCH http://localhost:3000/cart/by-product/1/br
Content-Type: application/json

{
  "quantity": 4
}



### update cart
PATCH http://localhost:3000/cart/93b40cc5-bbcc-4161-9f2b-3fec5c11fb30
Content-Type: application/json

{   
    "quantity": 200
}

### delete product
DELETE  http://localhost:3000/cart/46662d08-3ecd-4420-965b-14f1eaaadf8f
